cask_args appdir: '/Applications'

brew 'ack'
brew 'bazel'
brew 'coreutils'
brew 'dep'
brew 'fish'
brew 'fzf'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'mysql'
brew 'node'
brew 'neovim'
brew 'openssl'
brew 'protobuf'
brew 'reattach-to-user-namespace'
brew 'rbenv'
brew 'rbenv-vars'
brew 'telnet'
brew 'tmux'
brew 'the_platinum_searcher'
brew 'yarn'
brew 'vcprompt'

cask 'arduino'
cask 'docker'
cask 'caskroom/versions/java8'
cask 'minikube'
cask 'ngrok'
cask 'vlc'
cask 'visual-studio-code'
